#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'net/http'
require 'json'
require 'term/ansicolor'

class String
    include Term::ANSIColor

    def valid_float?
        true if Float self rescue false
    end
end

class Color
    extend Term::ANSIColor
end

class StreamJSON
    attr_accessor :server_location
    attr_accessor :id
    
    def initialize(server_location = "http://localhost:4881", id = nil)
        @server_location = server_location
        @id = id
    end
    
    private
    def get_video_list
        url = "#{@server_location}/list"
        resp = Net::HTTP.get_response URI.parse(url)
        
        JSON.parse resp.body
    end
    
    def put_video_detail(videos)
        selected = nil
        
        if @id.valid_float?
            selected = videos[@id.to_i]
        elsif @id.is_a? String
            selected = videos.select do |key, hash|
                key["id"] == @id
            end
            selected = selected[0]
        else
            puts "You've entered a invalid ID."
        end
        
        if selected.nil?
            # ID doesn't exist
            puts "You've entered a ID that doesn't exist on the list."
        else
            # Show the details
            # TODO: Display ANSI of the poster.
            print Color.bold, selected["title"], Color.clear, "\n\n"
            puts selected["description"]["text"]
        end
    end
    
    public
    def list
        # List videos.
        puts "Videos"
        
        videos = get_video_list
        videos["video"].each_with_index do |curr_video, index|
            print "    ", "#{index} ", "(#{curr_video["id"]})".cyan, ": ", "#{curr_video["title"]}".bold, "\n"
        end
    end
    
    def detail
        # Details on the video.
        videos = get_video_list["video"]
        put_video_detail videos
    end
    
    def play
        # Play video.
    end
end

if __FILE__ == $0
    streamjson = StreamJSON.new
    
    opt_parser = OptionParser.new do |opt|
        opt.version = "streamjson 0.1 (c) 2012 Nathan Campos\nThe awesome stream.json client for your awesome command-line."
        opt.banner = "Usage: streamjson option [id]"
        opt.separator ""
        opt.separator "Options"
        
        # List videos
        opt.on("-l", "--list", "List videos") do
            streamjson.list
        end
        
        # Detail video.
        opt.on("-d", "--detail id", "Display details of a video") do |id|
            streamjson.detail id
        end
        
        # Play video.
        opt.on("-p", "--play id", "Plays the video") do |id|
            streamjson.play id
        end
        
        # Usage
        opt.on("-h", "--help", "Help") do
            puts opt_parser
        end
    end
    
    if ARGV[0].nil?
        puts opt_parser
    else
        opt_parser.parse!
    end
end